### ISSUE TITLE
Compiling error for onnxruntime crate

### ISSUE THREAD

**Issue by heyong4725** [dora-rs/dora-sync-async-examples#1]
Environment: MacOS w/o GPU
When compiling the code per launch.sh (or README.md), I have following compiling error:

Compiling onnxruntime v0.0.12 (https://github.com/haixuanTao/onnxruntime-rs.git?branch=owned_environment#4ebef94d)
error[E0425]: cannot find function, tuple struct or tuple variant `OrtSessionOptionsAppendExecutionProvider_CUDA` in crate `sys`
   --> /Users/yonghe/.cargo/git/checkouts/onnxruntime-rs-e7f04006ae5eea37/4ebef94/onnxruntime/src/session.rs:129:18
    |
129 |             sys::OrtSessionOptionsAppendExecutionProvider_CUDA(
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `sys`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `onnxruntime` due to previous error

Can you take a look? @haixuanTao

**Comment by haixuanTao** [comment]
I see. So I have put GPU capabilities under feature flag. https://github.com/dora-rs/dora-sync-async-examples/commit/6c5545d4979d56bfa2b509ce0b1c62e37d790294

Let me know if you still have difficulties compiling this crate.

**Comment by heyong4725** [comment]
@haixuanTao I can compile the crate now!

But when I run the dataflow: ./bin/dora-coordinator run ./dataflow.yml
I have the following error:
None
None
None
Error: unknown output

Location:
    /Users/yonghe/.cargo/git/checkouts/dora-865db9b4eb79312d/cd4089b/api/rust/node/src/lib.rs:105:13
Error: failed to run dataflow at ./dataflow.yml

Caused by:
   0: custom node failed
   1: node sender failed with exit code: 1

Location:
    coordinator/src/main.rs:137:17

For this example to run, do we need onnxruntime?

**Comment by haixuanTao** [comment]
I think that the problem might be that you don't have the latet version of `dora-sync-async-examples`. I probably have updated the dataflow definition since your last pull. Could you try to pull again? And just run the 

```bash
./bin/dora-coordinator run ./dataflow.yml
```

Thanks for your patience :)

**Comment by haixuanTao** [comment]
So, I have removed `onnxruntime` as a required dependencies. I am not sure that the current `rust` wrapper can handle mac and if it can, it will depend on the type of macbook you have whether it is `intel` or mac `m1`. 

I have left the code in case, I want to switch quickly from CPU to GPU.

**Comment by heyong4725** [comment]
I am on Intel MacBook Pro.

I did git pull, then:
cargo build --all --release
./bin/dora-coordinator run ./dataflow.yml

But similar error: 
None
None
None
Error: No such file or directory (os error 2)

Location:
    sender/src/main.rs:31:15
Error: failed to run dataflow at ./dataflow.yml

Caused by:
   0: custom node failed
   1: node sender failed with exit code: 1

Location:
    coordinator/src/main.rs:137:17
~/GitHub/dora-rs/dora-sync-async-examples $ 
@haixuanTao

**Comment by haixuanTao** [comment]
I see. So this error was linked to a change in the name of a downloaded image. I have made the downloading of data part of the common crate, to check if the data has correctly been downloaded and if not to fo fetch it. This will hopefully reduce the risk that your current error happen again.

I have also put the current `README` bash script under CI Test, and as the CI Test is passing, you should normally not have any more issues with the installation of this repository.

However if you still do, i would suggest to delete the cloned repo and do:
```bash
git clone https://github.com/dora-rs/dora-sync-async-examples.git
cd dora-sync-async-examples
chmod +x .github/setup.sh
.github/setup.sh
./bin/dora-coordinator run .github/test-dataflow.yml
```

This should normally work and you will then be able to modify either the dataflow or the different crates-runtime to your liking.

I think that it's good to have this type of crate to really put into practice what we develop at `dora`.

**Comment by heyong4725** [comment]
It works now. Thanks @haixuanTao 
I am closing the issue.
